---
# tasks file for docker
 - name: Update apt cache
   apt: update_cache=yes

 - name: Add docker group for convenience (add your own users)
   group: name=docker state=present
 
 - name: Install pre-reqs
   apt: name={{ item }} state=installed
   with_items:
     - apt-transport-https
     - ca-certificates

 - name: Add apt key
   apt_key:
     keyserver: hkp://p80.pool.sks-keyservers.net:80
     id: 58118E89F3A912897C070ADBF76221572C52609D
 
 # - name: Edit apt sources
 #   template:
 #     src: docker.list.j2
 #     dest: /etc/apt/sources.list.d/docker.list 
 - name: Add apt repo
   apt_repo: 
     repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ release }} main' 
     filename: docker
     update_cache: yes 
     state: present

 - name: Purge old copy (if exists)
   apt: name=lxc-docker purge=yes state=absent

 - name: Install linux-image-extra if arch needs it
   apt: name=linux-image-extra-{{ ansible_kernel }}
   when: release in ['xenial', 'trusty', 'wily']
   notify:
     - Restart server
     - Wait for server to restart


 - name: Install apparmor if necessary
   apt: name=apparmor
   when: release in ['trusty', 'precise']
   
 - name: Update kernel if we're in precise
   apt: name={{ item }}
   with_items:
     - linux-image-generic-lts-trusty
     - linux-headers-generic-lts-trusty
   when: release == 'precise'
   notify:
     - Restart server
     - Wait for server to restart

 - name: Install graphical env stuff if we're in precise and we need it
   apt: name={{ item }}
   with_items:
     - xserver-xorg-lts-trusty
     - libgl1-mesa-glx-lts-trusty
   when: release == 'precise' and has_gui

 - name: Install docker (finally!)
   apt: name=docker-engine
